### ISSUE TITLE
testing pipeline build failure

### ISSUE THREAD

**Issue by e-papanicolas** [clearviction-devs/clearviction-wa#232]
The github actions testing pipeline build job is failing on the cache step. It looks like `actions/cache@3.3.2` uses node v16 under the hood. A [newer version](https://github.com/actions/cache) is available and would probably easily resolve this.

<img width="1003" alt="Screenshot 2024-03-25 at 5 36 00 PM" src="https://github.com/clearviction-devs/clearviction-wa/assets/76261375/a1e56dbd-44fa-4d04-9345-aaf0c8ffdbe1">
<img width="1333" alt="Screenshot 2024-03-25 at 5 34 47 PM" src="https://github.com/clearviction-devs/clearviction-wa/assets/76261375/f9b6763b-a773-4269-8eeb-a0fd6430bd0e">

**Comment by LeoFuna** [comment]
Thx for have an suggestion on how to resolve this, your suggestion worked!
